# COPIED FROM .ENV - PASTE THIS INTO STREAMLIT SECRETS
# -----------------------------------------------------

SUPABASE_URL = "https://ykzcwprttmaaomqmlizy.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlremN3cHJ0dG1hYW9tcW1saXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMTQ1MzQsImV4cCI6MjA3OTg5MDUzNH0.LAMeLLfEbMQ0a8lNJApdKtCQ0tMYxathGk7z5wsOFVA"
GOOGLE_API_KEY = "AIzaSyAzr9GCpA1ZOmFIS3wSAJg_f4xYMnxK9HI"
FMP_API_KEY = "vi27teaopbJgjfFyGFLesXX8B91OT7mU"
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1452359379650216076/u5ymBZMW2qKC-a9niBS6B7_c9FgMr4fYwoI2c1PWrwRoogJ7qJRvCGo-exWGoXAHpG9K"
